[2024-10-22T23:08:47.405+0000] {processor.py:161} INFO - Started process (PID=9911) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:08:47.410+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:08:47.416+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:08:47.414+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:08:47.426+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:08:47.419+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 13
    def get_history():
                      ^
IndentationError: expected an indented block after function definition on line 13
[2024-10-22T23:08:47.428+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:08:47.537+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.150 seconds
[2024-10-22T23:09:02.305+0000] {processor.py:161} INFO - Started process (PID=9921) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:09:02.308+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:09:02.321+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:09:02.319+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:09:02.335+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:09:02.329+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 13
    def get_history(ticker, ds, ds_nodash):
                                           ^
IndentationError: expected an indented block after function definition on line 13
[2024-10-22T23:09:02.338+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:09:02.419+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.148 seconds
[2024-10-22T23:09:32.491+0000] {processor.py:161} INFO - Started process (PID=9934) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:09:32.493+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:09:32.501+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:09:32.500+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:09:32.506+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:09:32.505+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 13
    def get_history(ticker, ds, ds_nodash):
                                           ^
IndentationError: expected an indented block after function definition on line 13
[2024-10-22T23:09:32.507+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:09:32.540+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.068 seconds
[2024-10-22T23:09:33.540+0000] {processor.py:161} INFO - Started process (PID=9935) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:09:33.541+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:09:33.547+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:09:33.546+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:09:33.551+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:09:33.550+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 14
    def get_history(ticker, ds=None, ds_nodash=None):
                                                     ^
IndentationError: expected an indented block after function definition on line 14
[2024-10-22T23:09:33.552+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:09:33.583+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.070 seconds
[2024-10-22T23:09:35.670+0000] {processor.py:161} INFO - Started process (PID=9936) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:09:35.674+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:09:35.684+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:09:35.682+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:09:35.697+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:09:35.691+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 15
    
    ^
IndentationError: expected an indented block after function definition on line 14
[2024-10-22T23:09:35.700+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:09:35.791+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.162 seconds
[2024-10-22T23:09:47.405+0000] {processor.py:161} INFO - Started process (PID=9938) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:09:47.411+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:09:47.432+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:09:47.428+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:09:47.461+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:09:47.449+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 16
    
    ^
IndentationError: expected an indented block after function definition on line 15
[2024-10-22T23:09:47.467+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:09:47.595+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.218 seconds
[2024-10-22T23:10:18.058+0000] {processor.py:161} INFO - Started process (PID=9951) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:10:18.061+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:10:18.069+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:10:18.067+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:10:18.081+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:10:18.076+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 16
    
    ^
IndentationError: expected an indented block after function definition on line 15
[2024-10-22T23:10:18.083+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:10:18.151+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.118 seconds
[2024-10-22T23:10:48.849+0000] {processor.py:161} INFO - Started process (PID=9964) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:10:48.850+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:10:48.853+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:10:48.853+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:10:48.858+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:10:48.857+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 16
    
    ^
IndentationError: expected an indented block after function definition on line 15
[2024-10-22T23:10:48.859+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:10:48.895+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.059 seconds
[2024-10-22T23:11:08.967+0000] {processor.py:161} INFO - Started process (PID=9977) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:11:08.969+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:11:08.973+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:11:08.973+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:11:08.980+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:11:08.978+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 17
    Path(file_path).parent.mkdir(parents=True, exist_ok=True)
IndentationError: unexpected indent
[2024-10-22T23:11:08.981+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:11:09.016+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.064 seconds
[2024-10-22T23:11:39.478+0000] {processor.py:161} INFO - Started process (PID=9990) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:11:39.481+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:11:39.490+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:11:39.489+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:11:39.503+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:11:39.499+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 17
    Path(file_path).parent.mkdir(parents=True, exist_ok=True)
IndentationError: unexpected indent
[2024-10-22T23:11:39.506+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:11:39.558+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.106 seconds
[2024-10-22T23:11:44.695+0000] {processor.py:161} INFO - Started process (PID=9991) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:11:44.697+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:11:44.702+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:11:44.701+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:11:44.710+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:11:44.708+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 1, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:11:44.711+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:11:44.744+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.076 seconds
[2024-10-22T23:11:50.858+0000] {processor.py:161} INFO - Started process (PID=9993) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:11:50.860+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:11:50.868+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:11:50.866+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:11:50.882+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:11:50.878+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 1, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:11:50.883+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:11:50.943+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.114 seconds
[2024-10-22T23:12:21.472+0000] {processor.py:161} INFO - Started process (PID=10012) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:12:21.475+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:12:21.480+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:12:21.479+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:12:21.489+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:12:21.487+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 1, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:12:21.490+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:12:21.556+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.101 seconds
[2024-10-22T23:12:51.932+0000] {processor.py:161} INFO - Started process (PID=10025) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:12:51.935+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:12:51.945+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:12:51.943+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:12:51.958+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:12:51.954+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 1, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:12:51.959+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:12:52.035+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.129 seconds
[2024-10-22T23:13:22.200+0000] {processor.py:161} INFO - Started process (PID=10038) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:13:22.205+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:13:22.210+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:13:22.209+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:13:22.222+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:13:22.219+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 1, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:13:22.223+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:13:22.265+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.077 seconds
[2024-10-22T23:13:52.576+0000] {processor.py:161} INFO - Started process (PID=10051) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:13:52.578+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:13:52.589+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:13:52.587+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:13:52.603+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:13:52.597+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 1, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:13:52.605+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:13:52.643+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.096 seconds
[2024-10-22T23:14:23.098+0000] {processor.py:161} INFO - Started process (PID=10065) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:14:23.104+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:14:23.115+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:14:23.113+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:14:23.135+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:14:23.128+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 1, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:14:23.139+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:14:23.243+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.172 seconds
[2024-10-22T23:14:45.004+0000] {processor.py:161} INFO - Started process (PID=10071) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:14:45.008+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:14:45.017+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:14:45.015+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:14:45.038+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:14:45.032+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:14:45.042+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:14:45.142+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.172 seconds
[2024-10-22T23:15:10.948+0000] {processor.py:161} INFO - Started process (PID=10084) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:15:10.953+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:15:10.968+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:15:10.965+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:15:10.993+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:15:10.986+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:15:10.996+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:15:11.092+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.191 seconds
[2024-10-22T23:15:41.696+0000] {processor.py:161} INFO - Started process (PID=10097) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:15:41.697+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:15:41.702+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:15:41.701+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:15:41.707+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:15:41.706+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:15:41.708+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:15:41.742+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.054 seconds
[2024-10-22T23:16:12.398+0000] {processor.py:161} INFO - Started process (PID=10110) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:16:12.401+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:16:12.409+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:16:12.407+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:16:12.421+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:16:12.417+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:16:12.423+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:16:12.488+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.114 seconds
[2024-10-22T23:16:42.571+0000] {processor.py:161} INFO - Started process (PID=10123) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:16:42.572+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:16:42.574+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:16:42.574+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:16:42.578+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:16:42.576+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:16:42.578+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:16:42.596+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.032 seconds
[2024-10-22T23:17:12.840+0000] {processor.py:161} INFO - Started process (PID=10136) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:17:12.842+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:17:12.850+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:17:12.848+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:17:12.860+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:17:12.857+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:17:12.861+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:17:12.891+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.075 seconds
[2024-10-22T23:17:43.109+0000] {processor.py:161} INFO - Started process (PID=10147) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:17:43.112+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:17:43.122+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:17:43.120+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:17:43.134+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:17:43.130+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:17:43.136+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:17:43.200+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.123 seconds
[2024-10-22T23:18:14.058+0000] {processor.py:161} INFO - Started process (PID=10160) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:18:14.060+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:18:14.069+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:18:14.068+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:18:14.089+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:18:14.082+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:18:14.092+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:18:14.191+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.170 seconds
[2024-10-22T23:18:44.373+0000] {processor.py:161} INFO - Started process (PID=10173) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:18:44.376+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:18:44.384+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:18:44.382+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:18:44.395+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:18:44.392+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:18:44.397+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:18:44.458+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.108 seconds
[2024-10-22T23:19:14.856+0000] {processor.py:161} INFO - Started process (PID=10187) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:19:14.857+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:19:14.861+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:19:14.861+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:19:14.866+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:19:14.865+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:19:14.867+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:19:14.888+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.045 seconds
[2024-10-22T23:19:45.436+0000] {processor.py:161} INFO - Started process (PID=10200) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:19:45.439+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:19:45.447+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:19:45.445+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:19:45.458+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:19:45.454+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:19:45.459+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:19:45.520+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.106 seconds
[2024-10-22T23:20:15.794+0000] {processor.py:161} INFO - Started process (PID=10213) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:20:15.796+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:20:15.804+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:20:15.802+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:20:15.815+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:20:15.811+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:20:15.817+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:20:15.877+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.106 seconds
[2024-10-22T23:20:46.270+0000] {processor.py:161} INFO - Started process (PID=10226) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:20:46.272+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:20:46.275+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:20:46.275+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:20:46.282+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:20:46.280+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:20:46.283+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:20:46.309+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.047 seconds
[2024-10-22T23:21:16.773+0000] {processor.py:161} INFO - Started process (PID=10239) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:21:16.776+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:21:16.784+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:21:16.783+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:21:16.797+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:21:16.793+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:21:16.799+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:21:16.868+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.118 seconds
[2024-10-22T23:21:47.432+0000] {processor.py:161} INFO - Started process (PID=10252) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:21:47.435+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:21:47.443+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:21:47.441+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:21:47.456+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:21:47.452+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:21:47.458+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:21:47.532+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.126 seconds
[2024-10-22T23:22:18.212+0000] {processor.py:161} INFO - Started process (PID=10265) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:22:18.213+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:22:18.215+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:22:18.214+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:22:18.218+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:22:18.217+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:22:18.218+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:22:18.239+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.034 seconds
[2024-10-22T23:22:48.934+0000] {processor.py:161} INFO - Started process (PID=10278) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:22:48.936+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:22:48.939+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:22:48.939+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:22:48.945+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:22:48.942+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:22:48.946+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:22:48.973+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.047 seconds
[2024-10-22T23:23:19.603+0000] {processor.py:161} INFO - Started process (PID=10291) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:23:19.607+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:23:19.618+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:23:19.616+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:23:19.637+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:23:19.630+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:23:19.640+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:23:19.734+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.169 seconds
[2024-10-22T23:23:50.618+0000] {processor.py:161} INFO - Started process (PID=10304) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:23:50.621+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:23:50.628+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:23:50.627+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:23:50.640+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:23:50.636+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:23:50.642+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:23:50.701+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.107 seconds
[2024-10-22T23:24:21.173+0000] {processor.py:161} INFO - Started process (PID=10317) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:24:21.175+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:24:21.183+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:24:21.181+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:24:21.194+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:24:21.191+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:24:21.196+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:24:21.259+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.109 seconds
[2024-10-22T23:24:51.479+0000] {processor.py:161} INFO - Started process (PID=10331) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:24:51.485+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:24:51.501+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:24:51.497+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:24:51.523+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:24:51.515+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:24:51.527+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:24:51.619+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.175 seconds
[2024-10-22T23:25:21.900+0000] {processor.py:161} INFO - Started process (PID=10344) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:25:21.902+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:25:21.909+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:25:21.908+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:25:21.913+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:25:21.912+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:25:21.914+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:25:21.951+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.062 seconds
[2024-10-22T23:25:52.633+0000] {processor.py:161} INFO - Started process (PID=10357) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:25:52.638+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:25:52.645+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:25:52.644+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:25:52.653+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:25:52.649+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:25:52.654+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:25:52.710+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.089 seconds
[2024-10-22T23:26:22.922+0000] {processor.py:161} INFO - Started process (PID=10370) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:26:22.929+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:26:22.950+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:26:22.946+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:26:22.989+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:26:22.977+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:26:22.994+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:26:23.169+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.309 seconds
[2024-10-22T23:26:53.698+0000] {processor.py:161} INFO - Started process (PID=10383) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:26:53.701+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:26:53.714+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:26:53.713+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:26:53.734+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:26:53.728+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:26:53.737+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:26:53.818+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.155 seconds
[2024-10-22T23:27:24.432+0000] {processor.py:161} INFO - Started process (PID=10396) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:27:24.435+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:27:24.447+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:27:24.445+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:27:24.467+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:27:24.460+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:27:24.469+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:27:24.555+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.156 seconds
[2024-10-22T23:27:55.051+0000] {processor.py:161} INFO - Started process (PID=10408) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:27:55.057+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:27:55.076+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:27:55.069+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:27:55.117+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:27:55.110+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:27:55.119+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:27:55.196+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.182 seconds
[2024-10-22T23:28:03.349+0000] {processor.py:161} INFO - Started process (PID=10416) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:28:03.351+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:28:03.362+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:28:03.361+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:28:03.379+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:28:03.372+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 34
    
    ^
IndentationError: expected an indented block after function definition on line 33
[2024-10-22T23:28:03.382+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:28:03.459+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.138 seconds
[2024-10-22T23:28:33.631+0000] {processor.py:161} INFO - Started process (PID=10429) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:28:33.632+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:28:33.637+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:28:33.636+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:28:33.644+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:28:33.642+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 34
    
    ^
IndentationError: expected an indented block after function definition on line 33
[2024-10-22T23:28:33.646+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:28:33.682+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.065 seconds
[2024-10-22T23:29:04.090+0000] {processor.py:161} INFO - Started process (PID=10442) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:29:04.094+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:29:04.104+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:29:04.102+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:29:04.121+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:29:04.116+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 34
    
    ^
IndentationError: expected an indented block after function definition on line 33
[2024-10-22T23:29:04.125+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:29:04.199+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.138 seconds
[2024-10-22T23:29:24.699+0000] {processor.py:161} INFO - Started process (PID=10448) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:29:24.702+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:29:24.713+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:29:24.711+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:29:24.739+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:29:24.732+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:29:24.742+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:29:24.835+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.163 seconds
[2024-10-22T23:29:54.956+0000] {processor.py:161} INFO - Started process (PID=10461) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:29:54.958+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:29:54.966+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:29:54.965+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:29:54.978+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:29:54.975+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:29:54.980+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:29:55.042+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.111 seconds
[2024-10-22T23:30:25.285+0000] {processor.py:161} INFO - Started process (PID=10475) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:30:25.287+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:30:25.292+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:30:25.292+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:30:25.299+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:30:25.298+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:30:25.300+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:30:25.349+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.080 seconds
[2024-10-22T23:30:56.313+0000] {processor.py:161} INFO - Started process (PID=10487) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:30:56.317+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:30:56.325+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:30:56.323+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:30:56.341+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:30:56.336+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:30:56.343+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:30:56.419+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.133 seconds
[2024-10-22T23:31:27.173+0000] {processor.py:161} INFO - Started process (PID=10498) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:31:27.176+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:31:27.188+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:31:27.186+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:31:27.206+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:31:27.200+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:31:27.208+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:31:27.305+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.168 seconds
[2024-10-22T23:31:58.024+0000] {processor.py:161} INFO - Started process (PID=10511) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:31:58.029+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:31:58.040+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:31:58.038+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:31:58.059+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:31:58.054+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:31:58.062+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:31:58.163+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.174 seconds
[2024-10-22T23:32:28.393+0000] {processor.py:161} INFO - Started process (PID=10524) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:32:28.396+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:32:28.405+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:32:28.403+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:32:28.421+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:32:28.416+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:32:28.422+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:32:28.497+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.137 seconds
[2024-10-22T23:32:59.465+0000] {processor.py:161} INFO - Started process (PID=10537) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:32:59.469+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:32:59.480+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:32:59.479+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:32:59.498+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:32:59.493+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:32:59.500+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:32:59.576+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.150 seconds
[2024-10-22T23:33:30.240+0000] {processor.py:161} INFO - Started process (PID=10550) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:33:30.245+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:33:30.254+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:33:30.252+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:33:30.271+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:33:30.265+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:33:30.273+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:33:30.340+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.134 seconds
[2024-10-22T23:34:01.033+0000] {processor.py:161} INFO - Started process (PID=10569) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:34:01.034+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:34:01.038+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:34:01.037+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:34:01.042+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:34:01.040+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:34:01.042+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:34:01.068+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.043 seconds
[2024-10-22T23:34:31.567+0000] {processor.py:161} INFO - Started process (PID=10583) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:34:31.570+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:34:31.578+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:34:31.576+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:34:31.591+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:34:31.587+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:34:31.593+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:34:31.656+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.115 seconds
[2024-10-22T23:35:02.423+0000] {processor.py:161} INFO - Started process (PID=10595) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:35:02.426+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:35:02.433+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:35:02.432+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:35:02.445+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:35:02.441+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:35:02.447+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:35:02.507+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.108 seconds
[2024-10-22T23:35:33.310+0000] {processor.py:161} INFO - Started process (PID=10608) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:35:33.313+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:35:33.321+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:35:33.320+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:35:33.334+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:35:33.330+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:35:33.336+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:35:33.407+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.127 seconds
[2024-10-22T23:36:04.103+0000] {processor.py:161} INFO - Started process (PID=10621) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:36:04.107+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:36:04.116+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:36:04.114+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:36:04.129+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:36:04.125+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:36:04.131+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:36:04.190+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.110 seconds
[2024-10-22T23:36:34.477+0000] {processor.py:161} INFO - Started process (PID=10634) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:36:34.479+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:36:34.487+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:36:34.486+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:36:34.500+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:36:34.496+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:36:34.502+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:36:34.568+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.117 seconds
[2024-10-22T23:37:05.493+0000] {processor.py:161} INFO - Started process (PID=10647) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:37:05.497+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:37:05.506+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:37:05.504+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:37:05.522+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:37:05.517+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:37:05.525+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:37:05.597+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.134 seconds
[2024-10-22T23:37:36.219+0000] {processor.py:161} INFO - Started process (PID=10660) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:37:36.222+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:37:36.230+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:37:36.228+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:37:36.242+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:37:36.238+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:37:36.244+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:37:36.304+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.108 seconds
[2024-10-22T23:38:07.242+0000] {processor.py:161} INFO - Started process (PID=10673) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:38:07.244+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:38:07.247+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:38:07.246+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:38:07.251+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:38:07.250+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:38:07.252+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:38:07.275+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.041 seconds
[2024-10-22T23:38:38.324+0000] {processor.py:161} INFO - Started process (PID=10686) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:38:38.327+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:38:38.335+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:38:38.334+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:38:38.349+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:38:38.344+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:38:38.350+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:38:38.409+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.112 seconds
[2024-10-22T23:39:08.786+0000] {processor.py:161} INFO - Started process (PID=10699) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:39:08.789+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:39:08.797+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:39:08.795+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:39:08.809+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:39:08.805+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:39:08.812+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:39:08.874+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.112 seconds
[2024-10-22T23:39:39.825+0000] {processor.py:161} INFO - Started process (PID=10712) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:39:39.828+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:39:39.836+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:39:39.834+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:39:39.849+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:39:39.844+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:39:39.851+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:39:39.925+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.122 seconds
[2024-10-22T23:40:10.693+0000] {processor.py:161} INFO - Started process (PID=10725) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:40:10.702+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:40:10.704+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:40:10.704+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:40:10.708+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:40:10.707+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:40:10.709+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:40:10.731+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.045 seconds
[2024-10-22T23:40:41.449+0000] {processor.py:161} INFO - Started process (PID=10738) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:40:41.453+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:40:41.464+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:40:41.462+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:40:41.486+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:40:41.482+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:40:41.488+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:40:41.561+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.159 seconds
[2024-10-22T23:41:11.929+0000] {processor.py:161} INFO - Started process (PID=10751) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:41:11.932+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:41:11.941+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:41:11.939+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:41:11.953+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:41:11.950+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:41:11.955+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:41:12.028+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.123 seconds
[2024-10-22T23:41:42.530+0000] {processor.py:161} INFO - Started process (PID=10764) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:41:42.533+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:41:42.540+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:41:42.539+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:41:42.554+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:41:42.550+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:41:42.556+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:41:42.616+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.109 seconds
[2024-10-22T23:42:13.348+0000] {processor.py:161} INFO - Started process (PID=10777) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:42:13.352+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:42:13.360+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:42:13.359+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:42:13.377+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:42:13.372+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:42:13.379+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:42:13.442+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.117 seconds
[2024-10-22T23:42:43.970+0000] {processor.py:161} INFO - Started process (PID=10790) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:42:43.971+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:42:43.974+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:42:43.973+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:42:43.979+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:42:43.978+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:42:43.980+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:42:44.014+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.052 seconds
[2024-10-22T23:43:14.267+0000] {processor.py:161} INFO - Started process (PID=10803) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:43:14.268+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:43:14.271+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:43:14.271+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:43:14.277+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:43:14.275+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:43:14.278+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:43:14.326+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.068 seconds
[2024-10-22T23:43:44.953+0000] {processor.py:161} INFO - Started process (PID=10816) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:43:44.958+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:43:44.966+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:43:44.965+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:43:44.979+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:43:44.975+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:43:44.981+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:43:45.059+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.130 seconds
[2024-10-22T23:44:15.541+0000] {processor.py:161} INFO - Started process (PID=10829) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:44:15.543+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:44:15.553+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:44:15.551+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:44:15.565+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:44:15.561+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:44:15.567+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:44:15.627+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.113 seconds
[2024-10-22T23:44:46.401+0000] {processor.py:161} INFO - Started process (PID=10842) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:44:46.404+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:44:46.414+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:44:46.412+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:44:46.432+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:44:46.425+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:44:46.434+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:44:46.502+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.127 seconds
[2024-10-22T23:45:16.640+0000] {processor.py:161} INFO - Started process (PID=10854) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:45:16.642+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:45:16.650+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:45:16.648+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:45:16.662+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:45:16.658+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:45:16.664+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:45:16.745+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.130 seconds
[2024-10-22T23:45:47.523+0000] {processor.py:161} INFO - Started process (PID=10867) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:45:47.527+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:45:47.534+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:45:47.533+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:45:47.548+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:45:47.543+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:45:47.549+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:45:47.612+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.113 seconds
[2024-10-22T23:46:18.078+0000] {processor.py:161} INFO - Started process (PID=10880) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:46:18.081+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:46:18.089+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:46:18.087+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:46:18.104+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:46:18.099+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:46:18.106+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:46:18.181+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.127 seconds
[2024-10-22T23:46:48.710+0000] {processor.py:161} INFO - Started process (PID=10893) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:46:48.711+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:46:48.715+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:46:48.715+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:46:48.722+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:46:48.720+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:46:48.723+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:46:48.756+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.059 seconds
[2024-10-22T23:47:19.390+0000] {processor.py:161} INFO - Started process (PID=10904) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:47:19.405+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:47:19.411+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:47:19.410+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:47:19.427+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:47:19.424+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:47:19.433+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:47:19.613+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.254 seconds
[2024-10-22T23:47:50.460+0000] {processor.py:161} INFO - Started process (PID=10918) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:47:50.462+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:47:50.469+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:47:50.468+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:47:50.480+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:47:50.477+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:47:50.481+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:47:50.547+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.105 seconds
[2024-10-22T23:48:21.370+0000] {processor.py:161} INFO - Started process (PID=10931) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:48:21.373+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:48:21.380+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:48:21.379+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:48:21.393+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:48:21.389+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:48:21.395+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:48:21.458+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.112 seconds
[2024-10-22T23:48:51.911+0000] {processor.py:161} INFO - Started process (PID=10944) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:48:51.915+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:48:51.923+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:48:51.922+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:48:51.936+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:48:51.932+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:48:51.937+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:48:52.003+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.115 seconds
[2024-10-22T23:49:22.122+0000] {processor.py:161} INFO - Started process (PID=10957) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:49:22.123+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:49:22.127+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:49:22.126+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:49:22.138+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:49:22.134+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:49:22.140+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:49:22.209+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.097 seconds
[2024-10-22T23:49:52.582+0000] {processor.py:161} INFO - Started process (PID=10969) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:49:52.585+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:49:52.592+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:49:52.591+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:49:52.605+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:49:52.601+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:49:52.606+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:49:52.674+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.116 seconds
[2024-10-22T23:50:23.447+0000] {processor.py:161} INFO - Started process (PID=10982) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:50:23.450+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:50:23.457+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:50:23.456+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:50:23.469+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:50:23.466+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:50:23.471+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:50:23.538+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.114 seconds
[2024-10-22T23:51:49.313+0000] {processor.py:161} INFO - Started process (PID=59) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:51:49.316+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:51:49.325+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:51:49.322+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:51:49.338+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:51:49.330+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:51:49.341+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:51:49.464+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.162 seconds
[2024-10-22T23:52:19.582+0000] {processor.py:161} INFO - Started process (PID=72) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:52:19.584+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:52:19.588+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:52:19.587+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:52:19.598+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:52:19.596+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:52:19.600+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:52:19.640+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.073 seconds
[2024-10-22T23:52:49.790+0000] {processor.py:161} INFO - Started process (PID=85) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:52:49.796+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:52:49.804+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:52:49.801+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:52:49.875+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:52:49.859+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:52:49.877+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:52:50.012+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.270 seconds
[2024-10-22T23:53:20.310+0000] {processor.py:161} INFO - Started process (PID=98) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:53:20.317+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:53:20.324+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:53:20.323+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:53:20.376+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:53:20.345+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:53:20.378+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:53:20.536+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.421 seconds
[2024-10-22T23:53:51.102+0000] {processor.py:161} INFO - Started process (PID=111) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:53:51.110+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:53:51.144+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:53:51.142+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:53:51.182+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:53:51.176+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:53:51.186+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:53:51.407+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.390 seconds
[2024-10-22T23:54:21.555+0000] {processor.py:161} INFO - Started process (PID=124) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:54:21.558+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:54:21.563+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:54:21.561+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:54:21.582+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:54:21.578+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:54:21.584+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:54:21.638+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.105 seconds
[2024-10-22T23:54:52.377+0000] {processor.py:161} INFO - Started process (PID=138) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:54:52.378+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:54:52.383+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:54:52.382+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:54:52.392+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:54:52.390+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:54:52.393+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:54:52.442+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.079 seconds
[2024-10-22T23:55:23.067+0000] {processor.py:161} INFO - Started process (PID=151) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:55:23.068+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:55:23.073+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:55:23.071+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:55:23.081+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:55:23.079+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:55:23.083+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:55:23.114+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.060 seconds
[2024-10-22T23:55:53.528+0000] {processor.py:161} INFO - Started process (PID=164) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:55:53.529+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:55:53.531+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:55:53.530+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:55:53.534+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:55:53.533+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:55:53.535+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:55:53.565+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.043 seconds
[2024-10-22T23:56:24.245+0000] {processor.py:161} INFO - Started process (PID=177) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:56:24.248+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:56:24.256+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:56:24.255+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:56:24.272+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:56:24.267+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:56:24.275+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:56:24.349+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.136 seconds
[2024-10-22T23:56:55.073+0000] {processor.py:161} INFO - Started process (PID=196) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:56:55.076+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:56:55.086+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:56:55.084+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:56:55.103+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:56:55.097+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:56:55.106+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:56:55.180+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.127 seconds
[2024-10-22T23:57:26.166+0000] {processor.py:161} INFO - Started process (PID=210) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:57:26.172+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:57:26.186+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:57:26.184+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:57:26.213+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:57:26.206+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:57:26.215+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:57:26.346+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.234 seconds
[2024-10-22T23:57:57.096+0000] {processor.py:161} INFO - Started process (PID=221) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:57:57.102+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:57:57.125+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:57:57.121+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:57:57.149+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:57:57.142+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:57:57.152+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:57:57.248+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.191 seconds
[2024-10-22T23:58:27.528+0000] {processor.py:161} INFO - Started process (PID=234) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:58:27.531+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:58:27.539+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:58:27.538+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:58:27.554+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:58:27.549+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:58:27.556+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:58:27.628+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.127 seconds
[2024-10-22T23:58:58.560+0000] {processor.py:161} INFO - Started process (PID=247) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:58:58.562+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:58:58.570+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:58:58.568+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:58:58.582+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:58:58.578+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:58:58.584+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:58:58.645+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.109 seconds
[2024-10-22T23:59:29.418+0000] {processor.py:161} INFO - Started process (PID=260) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:59:29.421+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:59:29.429+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:59:29.427+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:59:29.445+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:59:29.441+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:59:29.447+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:59:29.512+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.118 seconds
[2024-10-22T23:59:59.897+0000] {processor.py:161} INFO - Started process (PID=273) to work on /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:59:59.901+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aula_4_1_get_stocks.py for tasks to queue
[2024-10-22T23:59:59.923+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:59:59.920+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-22T23:59:59.945+0000] {logging_mixin.py:188} INFO - [2024-10-22T23:59:59.941+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aula_4_1_get_stocks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aula_4_1_get_stocks.py", line 2, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
[2024-10-22T23:59:59.947+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aula_4_1_get_stocks.py
[2024-10-23T00:00:00.038+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aula_4_1_get_stocks.py took 0.187 seconds
